name: "Release"

on:
  push:
    branches:
      - beta
      - main

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true # ensure only one release workflow runs per branch (e.g., "release-beta" or "release-main")

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

# each job **MUST** run sequentially as a potential release will alter commit and push a CHANGELOG and bump its package version
jobs:
  bytes:
    name: "@agoralabs-sh/bytes"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "bytes"
      package_name: "@agoralabs-sh/bytes"
    secrets:
      NPM_TOKEN: ${{ secrets.PUBLISH_PUBLIC_PACKAGES_TOKEN }}

  uuid:
    needs: [bytes]
    name: "@agoralabs-sh/uuid"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "uuid"
      package_name: "@agoralabs-sh/uuid"
    secrets:
      NPM_TOKEN: ${{ secrets.PUBLISH_PUBLIC_PACKAGES_TOKEN }}

  # **MUST** come after uuid as it a dependency
  vip030026:
    needs: [uuid]
    name: "@agoralabs-sh/vip030026"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "vip030026"
      package_name: "@agoralabs-sh/vip030026"
    secrets:
      NPM_TOKEN: ${{ secrets.PUBLISH_PUBLIC_PACKAGES_TOKEN }}
